export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_ERROR = "GET_MOVIES_ERROR";

export const GET_DETAIL_MOVIE = "GET_DETAIL_MOVIE";
export const GET_DETAIL_MOVIE_SUCCESS = "GET_DETAIL_MOVIE_SUCCESS";
export const GET_DETAIL_MOVIE_ERROR = "GET_DETAIL_MOVIE_ERROR";
